### PR TITLE
Updated c13m4_cutthroatcreek navigation mesh

### PR DESCRIPTION
**Pull request by Kerouha**
By submitting, I acknowledge the topic has been discussed (issues or elsewhere), that I know what is required of compiled assets (CONTRIBUTING.md -> Coordination), and if these are text or script files I'll submit un-modifiied live game files first.

## What exactly is changed and why?

Changed navigation mesh of the final map of Cold Stream, because current nav file may predate the Cold Stream update itself.

There are places where nav areas are totally misaligned with the terrain, or completely out of bounds. Connections between some areas are blocked by level geometry and props.
This leads to things like infected mobs not attacking from certain directions, special infected getting stuck and killed off (Tanks in particular). Whole map areas are not being used by AI to full extent.
Survivor bots are affected in numerous places as well: they get stuck a lot when going up the watch tower stairs on their way to the helicopter, or near the boat after the large drop (just before Tank fight). This might be due to automatically generated navmesh being imprecise, tied to a grid.

Anyway, I touched up on the navmesh, fixing obvious errors that nav_trouble_report would give. Also remade navigation on that watch tower, inside the building with finale door and radio, and some other places.

## Survivor bots going up the watch tower (video)
[Original mesh (someone gets stuck almost every time)](https://youtu.be/zMHRYwUJrsU)

[video](https://youtu.be/zMHRYwUJrsU "video")

[Modified nav mesh](https://youtu.be/q9BbMIqNyuo)

[video](https://youtu.be/q9BbMIqNyuo "video")

## Is there anything specific that needs review? (Consider marking as a draft.)

You can check out the modified nav file by replacing the original one in `Left 4 Dead 2\update\maps`, and playing the map.
AFAIK there are basically no downsides to this change.
If you have some suggestions I can incorporate these and update the nav file.

## Does this address any open issues?

No, could not find any open issues regarding the state of Cold Stream nav mesh.

### CODE REVIEW

**Comment by Tsuey** [comment]
Just wanted to say the detail in this write-up is exceptional and highly appreciated! It'd be up to @Nesciuse for merging this or integrating stuff into our existing nav files, though overall, your detailed descriptions set a high standard.

**Comment by Nesciuse** [comment]
Sorry to be a let down but I am already aware of every listed issue and have a fixed up nav for this map. In general we don't plan merging external nav files so I recommend keeping nav related stuff in the issues section.

**Comment by Kerouha** [comment]
> Sorry to be a let down but I am already aware of every listed issue and have a fixed up nav for this map. In general we don't plan merging external nav files so I recommend keeping nav related stuff in the issues section.

In that case I would like to see the fixed version on the nav file by @Nesciuse 

If the fixed version does not feature changes that this pull request provides, or is edited in a way that may still impact AI behavior in a bad way, I will create appropriate issue.

It also may have some changes in areas that I did not account for. I will keep those in mind when doing further nav edits, or creating issues.

**Comment by Nesciuse** [comment]
Don't have plans to upload navs currently. But there are already several uploaded you can check out for issues

**Comment by alexiscoutinho** [comment]
@Kerouha https://github.com/Tsuey/L4D2-Community-Update/tree/master/root/maps

**Comment by Kerouha** [comment]
Coming to a conclusion that significant overhauls to navigation meshes are unlikely to be featured in a update (due to either Valve or this project's policies), this PR will be closed.

**Comment by alexiscoutinho** [comment]
@Kerouha Significant navmesh overhauls require extensive vetting to make sure they don't noticeably impact survival. Furthermore, our interaction time with Valve is limited these years. But we hope that one day conditions will allow for these kinds of changes and the nav files already in this repo are a testament to that. We'll need patience until then.

**Comment by Kerouha** [comment]
I've been made aware of this already.
Also, it would be handy if all of the allegedly fixed nav files were uploaded (at least as a fork/branch), so other people can provide feedback and give suggestions.

**Comment by alexiscoutinho** [comment]
Do you mean uploaded as a workshop item?

**Comment by Kerouha** [comment]
Create a separate branch, which won't conflict with "main" and can be updated with it
image

**Pull request closed without merging**
