### PR TITLE
Enforce that mutations set the special cm_ DirectorOptions keys

### PR DESCRIPTION
**Pull request by alexiscoutinho**
By submitting, I acknowledge the topic has been discussed (issues or elsewhere), that I know what is required of compiled assets (CONTRIBUTING.md -> Coordination), and if these are text or script files I'll submit un-modified live game files first.

## What exactly is changed and why?

This PR extends #157 by simply prepending `cm_` to every eligible and appropriate Director option in mutation files (this excludes places where a comment explicitly justifies why `_cm` isn't used). This is because non-cm_ keys can be overridden by map/other scripts, for example. It also cleans up whitespaces in the new file.

## Is there anything specific that needs review?

No.

## Does this address any open issues?

No.

### CODE REVIEW

**Comment by Nesciuse** [comment]
Don't know what you mean by map scripts but anything that's in MutationOptions in modescript has priority over whatever is started with BeginScript input to director so don't see what this is fixing

**Comment by alexiscoutinho** [comment]
With "map scripts" I mostly meant "other scripts" which could change SessionOptions in the middle of a round. But from what I undestood, you make it seem like `cm_` is useless in general. Or did I misunderstand you (probably)? Besides, using `cm_` whenever possible in mutations is good practice...

**Comment by Nesciuse** [comment]
I am quite sure that any script that will add director options using SessionOptions can as well simply add cm_ and overwrite it anyway. So all this pr does is break someone’s script that for whatever reason decided to use SessionOptions in this way.

**Comment by alexiscoutinho** [comment]
No. Firstly, if someone changes a `cm_` option outside a mutation script, he likely just wants to break stuff and this case should be ignored. Secondly, I'm not breaking anything here, and you saying that is mildly offensive.

**Comment by Nesciuse** [comment]
If someone wanted to break stuff adding cm_ here doesn't stop him …

**Comment by alexiscoutinho** [comment]
Yes, that's why I said that case should be ignored/is irrelevant.

**Comment by Nesciuse** [comment]
No that’s why changing adding cm_ is irrelevant

**Comment by alexiscoutinho** [comment]
I'm not trying to prevent vandalism, I'm trying to prevent accidents.

**Comment by Nesciuse** [comment]
Not all director options have cm_ version so preventing accidents this way is just an excuse you just came up with. It can be  argued only the mutation specific ones that don’t have non-_cm version should be used to make it clear they are only mutation specific.

**Comment by Treescrub** [comment]
Closing this because of possible breaking changes without fixing an existing issue.

**Comment by alexiscoutinho** [comment]
That's fine. Although I was overly pessimistic in my comment in #311 (there is no problem with the `cm_` keys themselves introduced here, plus they're also widely used), the scope of this PR isn't ideal. This is because even though using the `cm_` keys helps to prevent accidents and makes the mutation more robust (as implied in the VDC [section description](https://developer.valvesoftware.com/wiki/L4D2_Director_Scripts#Mutation_Specific.2FRelated)), the affected scripts are among the ones that benefit the least from this. EMS mutations are not enabled by default in custom campaigns, therefore the accident of changing a Director option via `SessionOptions` instead of `DirectorOptions` in a map script, which I was trying to prevent, would pretty much never occur (it would be extremely unlikely that someone capable of extending support for these mutations would mess up the DOT). Besides, there's the inconvenience of increasing asymmetry in the scripts as some `cm_` keys were mixed together with normal ones and alignment had to be adjusted. Finally, the Holdout map scripts would also have to be updated since they change the base mutation options. In fact, this would break all stages of custom Holdout maps, which is unacceptable.

On the other hand, the change to `cm_ProhibitBosses` in the Nightmare mutation is degenerate since that key doesn't do anything in a survival base game and the key would be removed in a future PR anyways. So, all in all, I mostly agree with Nesciuse now.

**Pull request closed without merging**
