### PR TITLE
Updated Various Files

### PR DESCRIPTION
**Pull request by Rayman1103**
Navmesh:
- Various nav fixes for -9999 flow areas.
- Better bot nav in various maps.
- Fixed nav areas in order for the warp_to_checkpoint concommand to work properly for c1m2.
- Added c1streets place name to the ceda evac center area in c1m3.

Lump:
- Lump edits to account for changed weapon density values.
- Added a prop to make it easier for infected bots to navigate for c4m2 and c4m3.
- Added missing breakwall texture to wall in warehouse of c12m2.
- Removed unreachable pill spawn from c12m4.

l4d1.nut:
- Disabled water slowdown for L4D1 Survival.

community5.nut (Death's Door):
- Enabled B&W state when under 25% health.

mutation15.nut (Versus Survival):
- Made it auto-trigger any outputs on the entity used to start Survival if the pre-round timer expires.

mutation19.nut (Taaannnk!!):
- Players no longer need to wait for incapped Survivors in order to progress at areas like elevators.

tankrun.nut:
- The first map of a Campaign will now spawn two Tier 1 weapons near the start area if no other Tier 1's are nearby.
- Made it so Survivors are auto-revived instantly when incapacitated or hanging from a ledge.
- Car alarms will now spawn a Tank if triggered.
- Disabled water slowdown for all maps.
- Set Survivor revive health to 50.

instructor_lessons.txt:
- "Tank Claw" hint had incorrect binding "+attack2".
- "Tank Rock" hint had incorrect binding "+attack".
- "Jockey Leap" hint had the incorrect ability_use of "ability_spit", and now uses the correct "ability_leap".

Other:
- Added render coloring support to the Hunter, Smoker, Boomer and Charger models.
- Fixed Audio and Keyboard / Mouse menus in the Options flyout having broken navigation keys when trying to use the arrow keys or a controller.
- Gave the knife it's old slash pattern back.

### CODE REVIEW

**Comment by Accelerator74** [comment]
Hi. I would like to make a small remark from myself about: Update SI material files. I'm glad that you accepted this change, but made it a bit incomplete :)

Hunter is missing the same fix in files: `hunter_01_burned.vmt` and `hunter_l4d1_burned.vmt`. Without this, when the Hunter is set on fire, the render color (if changed) will disappear.



With modified files above:

**Comment by Accelerator74** [comment]
Also pay attention to the Smoker's tongue


With change in file `smoker_l4d1_tongue.vmt`

For the Smoker's model from l4d2, the language is ok, no change is required.

**Comment by Rayman1103** [comment]
> Hi. I would like to make a small remark from myself about: Update SI material files. I'm glad that you accepted this change, but made it a bit incomplete :)
> 
> Hunter is missing the same fix in files: `hunter_01_burned.vmt` and `hunter_l4d1_burned.vmt`. Without this, when the Hunter is set on fire, the render color (if changed) will disappear.

Oh I see, alright I'll get those files updated as well. Thanks for letting me know!

**Comment by alexiscoutinho** [comment]
I think the Death's Door change to remove the kit -> pills conversion will cause a huge backlash. This would be a major balance shift towards the easy side. People who like this mutation play it for the extra challenge, heck, there are even a couple of mutation combinations that incorporate DD for even more difficulty (even I made one). I know kits would still pop-up in gameplay, but this was not bad as it was rare and there was strategy on how to use them as best as possible. Without the conversion, the drive to save as much initial health as possible for future chapters would be gone as there would always be kits in the saferoom. I think most mutations in the workshop that use DD would not port this specific change (even though most don't even check if the original mutation has updated :P). I believe older mutations should only receive fixes and very minor gameplay/balance changes.

There seems to be a lot of good stuff in the files though. I'm especially excited about the nav updates!

**Comment by Rayman1103** [comment]
> I think the Death's Door change to remove the kit -> pills conversion will cause a huge backlash. This would be a major balance shift towards the easy side. People who like this mutation play it for the extra challenge, heck, there are even a couple of mutation combinations that incorporate DD for even more difficulty (even I made one). I know kits would still pop-up in gameplay, but this was not bad as it was rare and there was strategy on how to use them as best as possible. Without the conversion, the drive to save as much initial health as possible for future chapters would be gone as there would always be kits in the saferoom. I think most mutations in the workshop that use DD would not port this specific change (even though most don't even check if the original mutation has updated :P). I believe older mutations should only receive fixes and very minor gameplay/balance changes.
> 
> There seems to be a lot of good stuff in the files though. I'm especially excited about the nav updates!

Thank you for your feedback. The reason I re-added medkits was to allow clearing the new B&W state when health is low. That way the player can see color again until dropping below 25% health. I didn't think it would be a major change, seeing as the Survivors don't have any incaps, so they'd still die when their health reaches 0 anyway.

Though with medkits there's no temp health decay, so I suppose that can make things a bit easier.

I could change it so Medkits spawned in the world will remain as medkits, but medkits that are inside the saferoom would get converted into Pills. Would that be better? I could check if the nav area nearest to the medkit is marked as CHECKPOINT, and if so remove it and spawn Pills there instead.

**Comment by alexiscoutinho** [comment]
I think the kits' spawning should stay as it was, unless we get a consensus on the change. For example, finales would become a lot easier with medkits. If the team was temp health (even high temp health) when it reached the radio it would be forced to make very tough decisions to conserve the 4 pills and use them only when they need to move fast. Players would often literally play on Death's Door by remaining on 1hp to save their pills! The classic l4d1 finales really push temp health management. I can show you some videos where finales would be quite different with kits instead of pills. If you prefer, I can ask some members of the hardcore Death's Door community for their opinion.

I think leaving the players B&W after they are beaten is fine. I guess it would be interesting to be B&W with 20 perm health + 79 temp health. This (current) behavior makes B&W be a proxy for ~red health which is nice. B&W is like a **side effect** of ~red health. Players could still get color again by using the rare kits, defibs or respawning is the saferoom. All this would be a small balance change towards harder, but I think that's how it should always have been since it's more realistic and they community slowly gets tougher :)

**Comment by Rayman1103** [comment]
> I think the kits' spawning should stay as it was, unless we get a consensus on the change. For example, finales would become a lot easier with medkits. If the team was temp health (even high temp health) when it reached the radio it would be forced to make very tough decisions to conserve the 4 pills and use them only when they need to move fast. Players would often literally play on Death's Door by remaining on 1hp to save their pills! The classic l4d1 finales really push temp health management. I can show you some videos where finales would be quite different with kits instead of pills. If you prefer, I can ask some members of the hardcore Death's Door community for their opinion.
> 
> I think leaving the players B&W after they are beaten is fine. I guess it would be interesting to be B&W with 20 perm health + 79 temp health. This (current) behavior makes B&W be a proxy for ~red health which is nice. B&W is like a **side effect** of ~red health. Players could still get color again by using the rare kits, defibs or respawning is the saferoom. All this would be a small balance change towards harder, but I think that's how it should always have been since it's more realistic and they community slowly gets tougher :)

Alright, I've reverted the change and allowed Pills to replace Medkits again upon your feedback.

**Comment by alexiscoutinho** [comment]
@Rayman1103 Well... that was... at least... fast.

**Comment by alexiscoutinho** [comment]
@Rayman1103 What is the best way to compare nav files?

**Comment by alexiscoutinho** [comment]
@Rayman1103 What is the best way to compare nav files?

**Comment by shqke** [comment]
> @Rayman1103 What is the best way to compare nav files?

Probably to [parse](https://github.com/shqke/nav_test/blob/main/.github/navdump.py) two revisions and make a human-readable output on differences.

Do you need this feature?

**Comment by Derpduck** [comment]
> @Rayman1103 What is the best way to compare nav files?
@Nesciuse may have a tool for this.

**Comment by alexiscoutinho** [comment]
@shqke That would be much appreciated and very useful. I like following the nav changes and checking if something I disliked before was fixed or not. In that moment, I was thinking about comparing the files to see if an (git) issue could be closed if it was forgotten. But, in general, such functionality would be crucial for transparency with the community and accountability/documentation.

Furthermore, it could help me solve a mystery when I privately tweaked the nav for c10m5, but strangely the director broke (horde wouldn't spawn before and outside finale) after I made some simple area connections.

Finally, it would allow other people to post PRs with nav changes/propositions and others could easily verify the integrity and true scope of the changes.

**Comment by alexiscoutinho** [comment]
@shqke I was looking at your repo and I thought it would be awesome if somehow GitHub actions was implemented here to automatically spit out/commit a log of the changes whenever a nav file is update in a PR. The logs, of course, would need to be discarded somehow (ideally automatically) before the final merge.

**Comment by shqke** [comment]
These were exactly my intentions, especially with @Tsuey making an accent on transparency.

I haven't came up in terms whether it will actually be in demand, but since you're so eager to see it, I may finish it.

However, can't help but notice that it's not the place to continue discussing this subject further on. If you have questions/wishes/features to propose - please do so in [shqke/nav_test](https://github.com/shqke/nav_test/) instead.

**Comment by Tsuey** [comment]
> These were exactly my intentions, especially with @Tsuey making an accent on transparency.
> 
> I haven't came up in terms whether it will actually be in demand, but since you're so eager to see it, I may finish it.
> 
> However, can't help but notice that it's not the place to continue discussing this subject further on. If you have questions/wishes/features to propose - please do so in [shqke/nav_test](https://github.com/shqke/nav_test/) instead.

The community demand will be high because sometimes it's fun to just have cool tools. @Nesciuse does have a tool for diffing nav files, which we should either extend ShowUpdate() with or it'll be a self-contained thing.

We're making a small push from VScript map edits to LMP files, which would allow changing map geometry in some cases -- so there's a lot of research being done there, too, i.e. https://github.com/Tsuey/L4D2-BSP-Lump-Editing

In contrast, Valve performs their own diffs and verification and have stated they would not benefit from our tools. It's just important that we make a distinction (.gitignore?) between files that are going into the game (i.e. ShowUpdate() stuff), and files (diffs) that are not -- and this line will be blurry, so we'll figure things out as stuff is ready.

**Comment by alexiscoutinho** [comment]
I think the way it is now is good (only files inside `root` go in the game). I also think that a `changelogs`/`docs` folder could be created to nest the full detail nav (and maybe other binary) diffs. The bulk of that 8k lines file could go there aswell, leaving only a practical summary for the general public. I wonder if those 8k lines are relevant though since people who care about them would know they come directly from all those map fixes files, which are already quite human readable.

**Comment by Tsuey** [comment]
Will give `changelogs` a try for the "release" test version tomorrow. I'll move the 8k line changelog there soon, but it will always be incomplete since we had several changelogs:

https://steamcommunity.com/app/550/discussions/0/5671690972170785653/#c5671690972170855637

It's not pretty but may be a necessary evil for now -- the precise goal with Github is to reduce that chaos in the future. We don't have all the other Steam News changelogs here either.

**Comment by Tsuey** [comment]
@Rayman1103 great news, we have it all! (Talker files pending future commit)

Quick note that I reviewed all the changelogs we've exchanged outside of Github and the only entry missing, that you added files for -- which will be documented for upcoming v1.1.0 tester Release:

https://github.com/Tsuey/L4D2-Community-Update/blob/master/root/modes/l4d1coop.txt
https://github.com/Tsuey/L4D2-Community-Update/blob/master/root/modes/l4d1survival.txt

l4d1coop and l4d1survival mode files:

- Set the cvar z_tank_autoshotgun_dmg_scale 1.

**Comment by alexiscoutinho** [comment]
Fixes #47.

**Pull request merged**
