### PR TITLE
Fix mission fail after players lose control of their characters

### PR DESCRIPTION
**Pull request by alexiscoutinho**
By submitting, I acknowledge the topic has been discussed (issues or elsewhere), that I know what is required of compiled assets (CONTRIBUTING.md -> Coordination), and if these are text or script files I'll submit un-modified live game files first.

## What exactly is changed and why?

This PR simply configures `trigger_finale`s to fire an output that sets the cvar `sb_all_bot_game` to 1 after players lose control of their characters. This is to prevent an issue where the mission would fail if the only human players die **for whatever reason** in the outro. The cvar is reset when the credits end or when the outro is forcefully interrupted, by `!restart` for example, (via another output). This would render PR #277 obsolete and would be an alternative, more general, fix to #275.

**Extra motivations:**

This fix is deliberately very general as it aims to tackle the fundamental issue that players should never lose if the fail reason was not caused by their incompetence (if **everyone** dies or gets incapacitated in the outro, then the mission would still fail as expected). This would also fix custom finales besides sacrifice-type ones and also the coop + B&W Bill combo. For example, a custom finale that has an "accident" happen to the survivors during the outro after they get rescued. Suppose that the outro picks half (or none) of the remaining survivors to kill. If that half contains the only human players, then the fail issue would be avoided. I believe this issue fix should not be delegated to all map makers. If it's obscure enough that The Sacrifice doesn't address it, then why should random mappers be expected to deal with it?

Note also that this is not a complete fix to The Sacrifice finale as it would still be desirable to have an adaptable, sometimes shorter, outro sequence if the sacrificed person is allowed to die; or it would be desirable to have a trigger damage override akin to what #277 did to make sure the sacrificed person doesn't die (to match the lore that Bill crawls to the generator room...). These latter fixes, however, should be map specific patches.

## Is there anything specific that needs review?

No.

## Does this address any open issues?

No.

### CODE REVIEW

**Comment by Nesciuse** [comment]
I don't think we should attempt fixing custom maps. You can't be sure what they do. In this case if custom maps actually kills the survivors deliberately sb_all_bot_game 1 will stay 1 after the failure

**Comment by alexiscoutinho** [comment]
Potentially fixing custom maps is a side effect, remember this mainly fixes The Sacrifice. The cvar would only persist if the mission forcefully fails after the rescue. Is it even reasonable for any map to do this? I would think that it's more likely for a custom finale to kill everyone (say, the survivors nuked themselves and Raccoon City) but still give the win, somehow, than for a finale to purposely fail after rescue.

**Comment by Nesciuse** [comment]
Fixing it in sacrifice only is enough

**Comment by alexiscoutinho** [comment]
Tbh, I'm reluctant in adding another function to enforce that the cvar resets if the mission deliberately fails in the outro because it could make this implementation lose its appeal of simplicity for a rare exception that I don't even know if exists.

@Rayman1103 what do you think? Do you believe adding this extra function is necessary or overkill?

**Comment by alexiscoutinho** [comment]
@Nesciuse Added a failsafe for demonstration. Now the cvar is reset to its original value even if the outro is interrupted by !restart.

**Comment by Rayman1103** [comment]
We're closing this PR since changing Cvars during the outro via Outputs isn't the best method. It would be best as a C++ fix.

**Pull request closed without merging**
