### PR TITLE
Enforce correct type for boolean Director options

### PR DESCRIPTION
**Pull request by alexiscoutinho**
This PR simply enforces that boolean DirectorOptions keys are set with boolean literals. It also improves **consistency** by following the recent trend in the community mutations to switch to booleans. I separated the commits for the EMS mutations in case they should be treated differently. I also skipped RocketDude and Confogl as these are versioned mutations with their own repo.

### CODE REVIEW

**Comment by Nesciuse** [comment]
I thought you like saving every bit

**Comment by alexiscoutinho** [comment]
@Nesciuse I guess next (PR), I could remove all redundant whitespaces from these files to compensate for the added **bytes** here. 😄

**Comment by Tsuey** [comment]
Seems ok, I'd definitely agree that boolean is more readable in this case. I'll have @Rayman1103 take a final look.

If there is excess whitespace, there's literally no harm in trimming that if you're going to be submitting an updated file anyway.

Keep in mind though: the less files Valve has to look at, the better. We could probably scrutinize every file in the game in this way. They do diff everything. A lowkey concern of mine has even been the map script split -- they did not anxiously greenlight it, and acknowledged it'd make more work. I don't think any of us know how to approach the gamemodes.txt PR, for example.

**Comment by alexiscoutinho** [comment]
Although @Tsuey said "the less files Valve has to look at, the better", I've added/included mutation11, 14 and community3 in the whitespace removal batch since they're so small and to keep **consistency**. GunBrain and Shootzones also have whitespace issues, but I've left them out because I thought you might feel that I would be "pushing it". I hope I didn't ruin this PR with my perfectionism. :)

**Pull request merged**
