### PR TITLE
Convert _commentary.txt clips and props to VScript

### PR DESCRIPTION
**Pull request by Derpduck**
#### All Modes
* `_commentary_lower_windows_elevator`: Blocks standing in the out of bounds windows by the elevator
#### Non-Coop modes
* `_commentary_lower_windows`: Blocks standing in the out of bounds windows by the left-side balconies
#### Coop
* Unblocked all clips that prevented skips between floors
* `_commentary_lower_windows_*`: Kept original commentary blockers on the lower windows by left-side balconies
    * This assists skips to drop between the floors, allowing people to do the skips the same ways they would in the past
#### Versus
* `_commentary_balconyjump`: Blocks the skip at the right-side balcony to get directly to the elevator room
* `_commentary_elevator_window`: Blocks dropping down between floors by the elevators
    * Improved this clip
* `_commentary_windowdrop_*`: Blocks dropping down between floors on the left side of the building
    * Improved these clips
* `_commentary_ledgedrop_*`: Makes dropping between the ledges on the outside of the building harder
	* Adjusted to be angled clips so they can't be stood on. It was, and still is, possible to skip between floors here

#### All Modes
* Removed a redundant point_nav_attribute_region that set NOTHREAT by the one way drop
    * It is already saved into the nav

#### All Modes
* `_commentary_shortcut_storeceiling`: Blocks survivors from going into the Just for Kidz ceiling
* `_commentary_shortcut_storevent`: Blocks survivors from going into the Just for Kidz vent

#### All Modes:
* `_commentary_vendingmachines`: Blocks standing on the vending machines by the saferoom
* `_commentary_escape_windows`: Blocks standing on the windows by the mall exit
    * Changed to survivor only (from everyone)
* `_commentary_escape_door_physics`: Blocks physics objects going through the mall exit doors
	* Not sure what this is for specifically, blocking cans going out of bounds possibly?
* `_commentary_cornerledge`: Blocks standing on a small ledge in the corner
* `_commentary_elevatorcorner`: Blocks standing on a ledge by the elevator
	* Improved this clip
* `_commentary_fauntleroys_*`: Blocks standing on wooden supports by the Fauntleroy's store
	* Improved this clip
* `_commentary_infopanel`: Blocks standing on the info panel
	* **Needs review:** Jesus spot - Can be removed if fixed

#### All Modes
* `_commentary_motelroof_survivors`: Blocks survivors from standing on the motel roof
	* This was unintentionally unblocked for survivors on all modes to allow infected onto the roof in versus, as the clip blocked everyone
* `_commentary_slopetruck`: Blocks standing on the truck at the top of the slope by the saferoom
	* **Needs review:** Jesus spot - Can be removed if fixed

#### All Modes:
* Removed blocker that creates a perma-stuck spot by the trailers outside the warehouse and doesn't block anything in particular
* `_commentary_generatorlights`: Blocks standing on the generator lights before the warehouse
    * For some reason this is duplicated in the lump file
* `_commentary_traintunnel_*`: Blocks getting on the start of the train track and going into the tunnel
* `_commentary_carouselgate_stuck`: Prevents players from blocking the carousel gate from opening
	* Changed to block all and physics (from everyone)
* `_commentary_blockergap`: Prevents survivors getting out of bounds behind gap in clip before the carousel
* `_commentary_electricalbox`: Blocks standing on an electrical box before the carousel
	* **Needs review:** Jesus spot - Can be removed if fixed
#### Versus:
* `_nav_tol_hedge_*`: Prevents survivors from getting full distance points by jumping from the lights to the hedge
	* Navs are unblocked once survivors hit the trigger that removes the clips there
	* Blocker on lights here has been removed

#### All Modes
* `_commentary_permstuck_swanshelf`: Prevents players from getting stuck inside the swan under the shelves
	* **Needs review:** Tried improving it by allowing access to the swan instead of blocking it, but it is only possible to enter/exit from one side
* `_commentary_truckclimb_*`: Blocks climbing on the truck before the coaster
* `_commentary_electricalbox_*`: Blocks climbing on the electrical boxes before the coaster
#### Coop & Versus
* `_commentary_fencewalk_*`: Blocks walking along the fences to skip the start of the coaster, and blocks a jesus spot
	* **Needs review:** Would like to review these for improvements + jesus spot fix required
#### Coop
* Unblocked climbing on the coaster supports before the button
* Unblocked climbing on the rails at the start of the coaster
* Unblocked climbing on the supports before the tunnel
* Unblocked jumping on the bush after the bridge to skip the final section of the coaster
#### Versus
* Adjusted `_cliprework_scaffnuke_skipd` to fully block standing on the left railing at the top of the first ramp of the coaster, replacing the commentary blocker
* `_commentary_downramp_railing`: Blocks standing on the railing at the first downwards ramp of the coaster
* `_commentary_pretunnel_supports`: Blocks climbing on the supports before the tunnel
* `_commentary_shortcut_bush_*`: Blocks jumping on the bush after the bridge to skip the final section of the coaster
	* Improved this clip

#### All Modes
* `_commentary_permstuck_dumpsters_*`: Prevents survivors getting hit out of bounds by the dumpsters near the strength test game
	* Improved this clip, as it did not fully prevent getting out of bounds
* `_commentary_boostertree_*`: Blocks standing in the trees around the barn
#### Coop & Survival
* Unblocked shortcut to get on the barn roof by jumping on the generator lights
#### Versus
* `_commentary_shortcut_generator_*`: Blocks jumping on the generator lights to get on the barn roof

#### All Modes
* Removed now redundant clips on the truss by the tallest scaffolding
* `_commentary_infectedwindows`: Blocks getting in the room next to the stage

#### All Modes
* `_commentary_dock_ledge`: Blocks going from a ledge into the water by the button to call the ferry
* `_commentary_booster_crumpstore_a*`: Blocks standing on the roof of the 2 story store by the event
	* Improved this clip
* `_commentary_dockprops_*`: Props and clips on the docks by the event to block jesus spot
	* While the jesus spot is fixed, these props are good to keep in
	* Changed clip on pole to survivor only (from everyone)

#### Coop
* Removed clips blocking players from skipping the crashed plane event
* Skipping the plane door will cause the event to trigger shortly after
#### PVP Modes
* `_commentary_clipgap_postcrash`: Prevents infected from going out of bounds shortly after the crashed plane
#### Versus
* `_commentary_planeclimb_*`: Blocks jumping on the plane roof where the tail is broken off

#### Coop
* Unblocked a shortcut to get on a roof by jumping on a fire barrel
#### Versus
* `_commentary_shortcut_firebarrel_*`: Blocks a shortcut to get on a roof by jumping on a fire barrel
	* **Needs review:** Want to improve this but unsure how to do it as it is possible to get on this roof legitimately

#### All Modes
* `_commentary_permstuck_furniture`: Prevents a perma-stuck spot behind some furniture in the first big house
	* Improved this clip
* `_commentary_floorcollapse`: Blocks a jesus spot inside the house
	* Changed to survivor only (from everyone)
	* **Needs review:** Could potentially be removed, common seem to be able to path here somewhat, but tanks don't path well
#### Coop
* Unblocked the fence at the start of the town
#### Versus
* `_commentary_shortcut_startfence`: Blocks getting on the fence at the start of the town

#### All Modes
* Unblocked a table in the burger tank
	* The jesus spot here has been fixed
* Unblocked front of boat on the street by the ambulance
	* **Needs review:** These clips don't seem to serve any purpose, needs testing
* `_commentary_clipgap_water`: Blocks a gap in the clips by the water
* `_commentary_smoother_burgersuv_*`: Clipping to smooth movement on the SUV by the docks
* `_commentary_booster_burgertree_*`: Clipping on trees around the burger tank
	* Improved these clips
* `_commentary_edgeshrubs_*`: Blocks standing on some shrubs around the edge of the town
	* Changed to survivor only (from everyone)

#### All Modes
* `_nav_cornerledge`: Blocks standing on an unpathable ledge by the elevator
	* Replaces a commentary blocker, taken from map 3
* `_canefield_coneroof`: Renamed from `_canefield_coneroof_m2only`
	* Applied to map 3 to replace commentary blocker
* `_canefield_conewoof`: Renamed from `_canefield_conewoof_m2only`
	* Applied to map 3 to replace commentary blocker
* `_commentary_spool`: Blocks standing on a spool where commons have issues pathing
	* **Needs review:** No longer a jesus spot, but some pathing issues still exist, can be removed if nav is improved
* `_commentary_elevatorpipe`: Blocks standing on a pipe / ladder by the elevator
#### Coop
* Unblocked the shortcut to get in the factory early by jumping on the broken wall
* Unblocked the upper floors of the factory and the shortcut through the broken wall
#### Non-Coop Modes
* `_commentary_upperfactory_*`: Blocks standing on the upper section of the factory
	* Improved these clips
#### Versus
* `_commentary_factoryhopup_*`: Blocks getting in the factory early by jumping on the broken wall
	* Changed to survivor only (from everyone)

#### All Modes
* `_nav_cornerledge`: Renamed from `_nav_cornerledge_m3only`
	* Applied to map 2 to replace commentary blocker
* `_canefield_coneroof`: Blocks standing on the slanted roof in the cane field
	* Replaces a commentary blocker, taken from map 2
* `_canefield_conewoof`: Blocks standing on the slanted roof in the cane field
	* Replaces a commentary blocker, taken from map 2
* `_commentary_spool`: Blocks standing on a spool where commons have issues pathing
	* **Needs review:** Still a jesus spot on map 3
* `_commentary_elevatorpipe`: Blocks standing on a pipe / ladder by the elevator
#### Coop
* Unblocked the upper floors of the factory and the shortcut through the broken wall
#### Non-Coop Modes
* `_commentary_upperfactory_*`: Blocks standing on the upper section of the factory
	* Improved these clips

#### All Modes
* Removed irrelevant blockers in inaccessible parts of the map
* Unblocked front of boat on the street by the ambulance
	* **Needs review:** These clips don't seem to serve any purpose, needs testing
* `_commentary_edgeshrubs_*`: Blocks standing on some shrubs around the edge of the town
	* Changed to survivor only (from everyone)

#### All Modes
* Removed irrelevant blockers in inaccessible parts of the map
* Removed now redundant blocker on generator lights
	* TLS added an improved clip here
* Unblocked a table in the burger tank
	* The jesus spot here has been fixed
* Unblocked standing on a spot behind the dock
* `_commentary_clipgap_water`: Blocks a gap in the clips by the water
* `_commentary_smoother_burgersuv_*`: Clipping to smooth movement on the SUV by the docks
* `_commentary_booster_burgertree_*`: Clipping on trees around the burger tank
	* Improved these clips

#### All Modes
* Removed env_player_blocker `brush_route_cafe` that blocks players going through the path in the bar when it is closed
	* **Needs review:** Piggybacks on existing brush names in the same area but appears to be redundant
		* If the path is blocked then survivors can't go through it even without the blocker
		* It blocks ghost infected from going through the blocked path, but is never enabled on modes with player infected, and infected going through it wouldn't cause any issues
* `_commentary_shortcut_forsale_*`: Blocks the shortcut over the wall by the for sale building
* `_commentary_nav_bienville_windows`: Blocks getting on / inside the bienville building windows
* `_commentary_clipgap_redhouse`: Blocks an out of bound spot by the red house at the back of the final street
* `_commentary_electricalbox`: Blocks climbing on an electrical box by the end of the map
* `_commentary_clipgap_endsaferoom_*`: Blocks getting out of bounds by the end saferoom
	* Improved this clip
* `_commentary_clipgap_endfence`: Blocks getting on the fence and out of bounds by the end saferoom
	* Changed to survivor only (from everyone)
#### PVP Modes
* `_commentary_propladder_wall_*`: Prop ladder to prevent a perma-stuck spot behind the wall by the alley
* `_ladder_permstuck_endsaferoom`: Prevents a perma-stuck spot behind the fence by the end saferoom
	* Area was previously blocked by a commentary blocker (`_commentary_clipgap_endfence`)

#### All Modes
* `_commentary_fencegenerator`: Blocks standing on the generator before the alleyway
* `_commentary_electricalbox`: Blocks climbing on an electrical box at the event
* `_commentary_shortcut_station`: Blocks jumping through a gap in a fence to skip going through the bus station
	* **Coop Only:** This clip is removed when the event is stopped
#### Non-PVP Modes
* Unblocked standing on the fences in the alleyway
* Unblocked standing on the tent by the event
#### PVP Modes
* `_commentary_fencegates_*`: Blocks standing on the fences in the alleyway
* `_commentary_eventtent`: Blocks standing on the tent by the event

#### All Modes
* `_commonhop_rooftop`: Adjusted this clip to fully block the wooden wall
	* Replaces commentary blocker on the same wall
* `_commentary_shortcut_sewerroof`: Blocks getting on the roof by the sewer
* `_commentary_nav_parkingtruck_*`: Blocks standing on the trucks in the parking lot
	* **Needs review:** Can be removed if jesus spots are fixed
* `_commentary_oob_bridgeexplosion`: Blocks players from getting out of bounds in the area past the bridge explosion
	* **Needs review:** Could maybe be improved
* `_commentary_clipgap_bridge`: Blocks survivors getting stuck out of bounds under the bridge
#### Non-Versus Modes
* Unblocked the shortcut to jump over the barricade before the sewer
#### Versus
* `_commentary_shortcut_barricade_*`: Blocks a shortcut to jump over the barricade before the sewer
	* Improved these clips

#### All Modes
* `_commentary_poolwindow`: Blocks being able to get back up the one-way drop at the pool hall by jumping on a window
#### Coop
* Unblocked the right-side fence at the start of the map
#### Versus
* `_commentary_clipgap_rightfence`: Blocks jumping over the right-side fence at the start of the map
* `_commentary_sneakyhunter_endsaferoom`: Blocks a window infected can hide on top of in the end saferoom

#### All Modes
* Removed now redundant clips on fences after the apartments
	* TLS added improved clips here
* `_commonhop_awning`: Adjusted clip to replace commentary blocker
	* Commentary blocker here has been removed as it was redundant
* `_commentary_rayfordcollision`: Fixes lack of collision on some windows in the saferoom with a big hole behind them
	* Changed this clip to only cover the windows it needs to
	* Changed to all and physics (from everyone)
* `_commentary_clipgap_river_*` Blocks getting out of bounds around the river
	* Improved these clips
* `_commentary_clipgap_streetbarricade`: Blocks survivors getting out of bounds behind a barricade before the apartments
* `_commentary_clipgap_wedding`: Blocks an out of bounds perma-stuck near the wedding area
* `_commentary_clipgap_endsaferoom`: Blocks getting out of bounds on a roof near the end saferoom
	* **Needs review:** Could be unblocked with some infected clips + wrongways removed

#### All Modes
* Removed now redundant clips on fire escape
	* TLS added improved clips here
* `_commentary_minifinale_clip`: Blocks skipping the event by jumping through a gap in the fence
	* **Coop Only:** This clip is removed when the event is started

#### All Modes
* `_commentary_clipgap_turbinewindows`: Blocks going through the windows in the generator room to skip going down the elevator / get out of bounds
* `_commentary_warehousegenerator`: Blocks jumping on a generator in the warehouse
	* Originally intended to prevent getting in the windows here which were not blocked pre-TLS

#### All Modes
* Removed now redundant clip on window by the end saferoom
	* TLS added improved clips here

#### All Modes
* `_commentary_warehousegenerator`: Blocks jumping on a generator in the warehouse
	* Originally intended to prevent getting in the windows here which were not blocked pre-TLS

#### All Modes
* `_commentary_roofjump_hotel`: Blocks jumping to a ledge from the saferoom to get out of bounds
* `_commentary_roofjump_elec`: Blocks skipping the apartment by landing on an electrical box from the saferoom
	* **Needs review:** Might require a review because electrical box has no collision
	* Changed to survivor only (from everyone)
* `_commentary_roofjump_ledge`: Blocks skipping the apartment by dropping from a ledge in the saferoom
	* **Needs review:** This one could use some improvement, but unsure how best to change it currently
	* Changed to survivor only (from everyone)
* `_commentary_roofjump_ac_*`: Blocks skipping the apartment by jumping to the AC units from the saferoom
	* Improved these clips
* `_commentary_l4d1_acunit`: Adds an AC unit that was omitted in the L4D2 port because it is based on the versus version of the map
#### PVP Modes
* `_commentary_busstop`: Blocks getting on the bus stop

#### All Modes
* Removed now redundant clip on subway car
	* TLS added improved clips here
* `_commentary_stuckwarp_undersafe_*`: Blocks some stuck spots in the corner under the saferoom
* `_booster_windowandfence`: Extended to block standing on the nearby fence
	* Extended to replace commentary blocker
* `_unattackable_building_top`: Renamed from `_unattackable_building`
	* Extended to replace commentary blocker
	* Now blocks the rooftop fully, and line up with `_unattackable_building_bot` in versus
* `_commentary_electricalbox`: Blocks an electrical box at the end of the map that can be used to get out of bounds
#### PVP Modes
* `_unattackable_building_bot`: Blocks walking along a ledge to avoid the street at the end of the map

#### All Modes
* Removed a redundant everyone clip above the gas station
* `_commentary_washerwindow`: Blocks jumping in windows by the washer event
	* Improved this clip
* `_commentary_clipgap_gasfence`: Blocks getting out of bounds behind the gas station

#### All Modes
* `_commentary_vent_oob_*`: Blocks getting in the vents by the elevator

#### All Modes
* `_commentary_nav_unattackable_*`: Props blocking a spot infected can't path to
	* **Needs review:** Could be removed if nav is fixed

#### All Modes
* `_commentary_propladder_crate_*`: Prop ladder on a platform after the event

#### Coop
* Unblocked the radio tower roof
#### PVP Modes
* `_commentary_towerroof`: Blocks getting on the radio tower roof

### CODE REVIEW

**Comment by Tsuey** [comment]
Incredible work!

I suspect it's all good to go already, but I'll definitely review everything. I'm maybe unsure as to how we'll want to changelog all this, i.e. what are we not condensing to just "Converted _commentary.txt blockers to VScript".

**Comment by alexiscoutinho** [comment]
The commentary files will be removed in the final commit right?! to live only in history... like the `anv` files...

**Comment by Derpduck** [comment]
Now consider this ready to review/merge, however some clips will still need reviewing/updating in the future which I have listed below.

Clips that have been removed from coop, survival, etc. should also be reviewed by relevant teams.


#### c1m4_atrium
* `_commentary_infopanel`

#### c2m1_highway
* `_commentary_slopetruck`

#### c2m2_fairgrounds
* `_commentary_electricalbox`

#### c2m3_coaster
* `_commentary_permstuck_swanshelf`
* `_commentary_fencewalk_*`

#### c3m3_shantytown
* `_commentary_shortcut_firebarrel_*`

#### c3m4_plantation
* `_commentary_floorcollapse`

#### c4m1_milltown_a
* Unblocked front of boat on the street by the ambulance

#### c4m2_sugarmill_a
* `_commentary_spool`

#### c4m3_sugarmill_b
* `_commentary_spool`

#### c4m4_milltown_b
* Unblocked front of boat on the street by the ambulance

#### c5m1_waterfront
* Removed env_player_blocker `brush_route_cafe` that blocks players going through the path in the bar when it is closed

#### c5m3_cemetery
* `_commentary_nav_parkingtruck_*`
* `_commentary_oob_bridgeexplosion`

#### c6m1_riverbank
* `_commentary_clipgap_endsaferoom`

#### c8m1_apartments
* `_commentary_roofjump_elec`
* `_commentary_roofjump_ledge`

#### c8m5_rooftop
* `_commentary_nav_unattackable_*`

**Comment by Tsuey** [comment]
> however some clips will still need reviewing/updating in the future

Reviewed this again with respect to Navmesh and assigned Nescius PR #TBD for last of nav issues.

Self-assigned PR #TBD aims to accomplish the following:

- Pre-emptively remove the VScript clips for which nav will be fixed.
- Re-add any Commentary clips (like Hard Rain's boat) that served an atypical purpose, and improve others like c3m3 fire barrel
- Remove VScript make_props and move them to lump files, so they still appear when players opt-out of updates.
- Convert last remaining significant lump clips (like c8m2 Generator Room, or remove redundant c2m2 Generator clip) to VScript.

**Note:** The No Mercy 1 bus stop roof clip being changed to Coop-only seems especially trivial, but was included in changelog. May need to re-assess in the future exactly what is noteworthy enough for the changelog, depending on how many more TLS clips (after [this commit](https://github.com/Tsuey/L4D2-Community-Update/commit/5e22d0e0eeed399d73dfda0eb22c070d79ae5139) and [these changes](https://gist.github.com/Tsuey/ce36973493b6cf3fd7afd016e3d07604)) we move to Versus-only. Right now, anything where an ordinary in-game demonstration can show a difference, it's changelogged -- the exception is Navmesh change notes, which need Survival/speedrunner QA.

# Skipped

These "needs review" were skipped, where * is something we'll put on Github Projects later:

**c2m2** `_commentary_electricalbox`: Too high, too far off critical path, and gives glimpse out of bounds. Keep blocked.

**c2m3** * `_commentary_permstuck_swanshelf`: Can only escape from one side, which is OK, it's cute to allow access here; may be worth brush or prop_static lump edit in distant future.

**c3m4** `_commentary_floorcollapse`: Similar thin nearby outcrop is BSP clipped so it's only consistent we clip this. Keep blocked.

**c5m3** `_commentary_oob_bridgeexplosion`: Seems fine even though it is much larger than it needs to be, and Survivors are already blocked otherwise with BSP clips. Valve added this back in the day to prevent a Ghost Smoker from jumping over the fence to run toward end saferoom then fall and attack from underneath the map; Valve added `_commentary_clipgap_bridge` to block the alternative Survivor commonhop method for doing the same thing.

**c6m1** * `_commentary_clipgap_endsaferoom`: Re-visit for a distant future func_playerinfected_clip and prop_static wrongway re-work, plus needs NODRAW ugly covered up; minor compared to everything else we could open up.

**c8m1** `_commentary_roofjump_elec`: Should be OK that the electrical box doesn't have collision; maybe for a distant future prop_static lump edit.

**c8m1** * `_commentary_roofjump_ledge`: Seems fine as is; future brush lump edits could remove the offending BSP clip and re-think this fix.

**c8m5** `_commentary_nav_unattackable_*`: A crate and 4 pipe props to fix a godspot have become part of the map's visual identity and add interesting asymmetry from other side. Akin to keeping c3m1's dock shelf/boat/pole. Keep these propss.

**c5m1:**

`make_clip( "_brush_route_cafe", "Everyone", 1, "-4 -28 -56", "4 28 56", "-1692 -1988 -321" );`

Valve's `brush_route_cafe` (the env_player_blocker NOT the necessary func_brush) does seem useless. Ghost SI can go through this wooden door in Coop, but it's solid for VS Survival (and plain Survival if it's later changed to "mp_gamemode versus"). The pathway through the wooden door is blocked by both func_brush and func_nav_blocker, as Killing/Unblocking those is required to remove the "BLOCKED_SURVIVOR BLOCKED_ZOMBIE". The func_nav_blocker itself seems redundant, but we're not messing with that. Valve's blocker was never used here as a hackish way to prevent spawns (it's too thin), it seems completely useless, keep it deleted. May exist due to crossed wires when cutting this Survival map, or the map was recompiled without updating its _commentary.txt. The door is already solid in VS Survival, which is the only place it's helpful in terms of directing players away from a bad spawn.

**Comment by Tsuey** [comment]
> c4m1_milltown_a
> 
>     Unblocked front of boat on the street by the ambulance
> 
> c4m4_milltown_b
> 
>     Unblocked front of boat on the street by the ambulance

I mentioned this briefly above a year ago but just so we don't forget:

In reviewing this PR again (to see what non-commentary "unblocks" might work best to ship sooner), I think the only persisting issue is that the above clips serve to fix stuck spots. They are a bit tricky to get stuck in, and far larger than needed to fix the stuck spot, but we'll need to get these re-added sometime. 

@ `setpos_exact 807 5826 101; setang_exact 8 3 0`

**Comment by Derpduck** [comment]
Good to know, I couldn't reproduce getting stuck in them myself but it's not a problem to re-do the clips

**Pull request merged**
