### PR TITLE
Fix mutations to respect SI count and fix Flu Season boomer damage

### PR DESCRIPTION
**Pull request by TrueVoidwalker**
By submitting, I acknowledge the topic has been discussed (issues or elsewhere), that I know what is required of compiled assets (CONTRIBUTING.md -> Coordination), and if these are text or script files I'll submit un-modifiied live game files first.

## What exactly is changed and why?

All standard co-op mutations that modify Special Infected maximums (Bleed Out, Hard Eight, Hunting Party, and Flu Season) will now respect campaign map that temporarily disable SI spawns before activating a finale.

Additionally, the gamemodes.txt file has had the quotations around all cvar overrides removed for consistency, as well as removing random extra spacing in front of a couple cvars. A number of gamemodes already didn't include quotes around cvar overrides in the first place, such as realism and a few mutations, and it was inconsistent which ones actually did or didn't have them.

This will also now fix Boomers dealing less-than-intended claw damage in the Flu Season mutation.

## Is there anything specific that needs review? (Consider marking as a draft.)

No.

## Does this address any open issues?

No.

### CODE REVIEW

**Comment by Derpduck** [comment]
Thanks for the pull request, I just wanted to highlight a few issues:

- An unmodified version of `gamemodes.txt` should be committed first so that we have visibility of the changes
- Changes should be limited to only those affecting gameplay, editing script/text files to remove white-space and quotations is unnecessary and makes parsing actual changes more difficult
- Some of the methods could be improved, you should store `Director.GetMapName()` in a variable instead of calling it 3 separate times, and use `GetDifficulty()` or `GetDifficultyString()` instead of the current method and use a switch loop to check it
- Hard coding the map names for the max specials means the issue still exists on custom maps, and leaves out other places where spawns are disabled (e.g. Parish 2), and mutations usually override the default spawning behavior anyway

**Comment by TrueVoidwalker** [comment]
ah, I wasn't sure if there was something weird with the `GetDifficulty()` function since for Tank Run difficulty was grabbed in such a weird way.

**Comment by alexiscoutinho** [comment]
Revives #303. Partially duplicates rejected #165. Therefore, it is undesirable to have the cosmetic gamemodes.txt changes.

**Comment by alexiscoutinho** [comment]
@Derpduck Regarding the 4th point, do you mean that a more general solution that checks whenever a local or map script disables special spawning would be more adequate? Also, sure, mutations do override the default spawning behavior, but out of simplicity or "sloppyness". Standard finales already disable spawning by default in the finale area, therefore mutations should respect areas that are designed to serve as a staging area as is the case with c5m5 and c6m3.

**Comment by alexiscoutinho** [comment]
Gonna start pinging people on Discord...

**Pull request merged**
